const images = {
  player_song_cover: require("./song_cover_album.jpg"),
  Liked_songs: require("./liked_songs.jpg"),
  SugAlbum1: require("./album1.jpeg"),
  SugAlbum2: require("./album2.jpeg"),
  SugAlbum3: require("./album3.jpeg"),
  SugAlbum4: require("./album4.jpeg"),
  SugAlbum5: require("./album5.jpeg"),
  SugAlbum6: require("./album6.jpeg"),
  SugAlbum7: require("./album7.jpeg"),
  SugAlbum8: require("./album8.jpeg"),
  Sug2Song1: require("./song1.jpeg"),
  Sug2Song2: require("./song2.jpeg"),
  Sug2Song3: require("./song3.jpeg"),
  Sug2Song4: require("./song4.jpeg"),
  Sug2Song5: require("./song5.jpeg"),
  Sug2Song6: require("./song6.jpeg"),
  Sug2Song7: require("./song7.jpeg"),
  Sug2Song8: require("./song8.jpeg"),
  Sug3Song1: require("./music1.jpeg"),
  Sug3Song2: require("./music2.jpeg"),
  Sug3Song3: require("./music3.jpeg"),
  Sug3Song4: require("./music4.jpeg"),
  Sug3Song5: require("./music5.jpeg"),
  Sug3Song6: require("./music6.jpeg"),
  Sug3Song7: require("./music7.jpeg"),
  Sug3Song8: require("./music8.jpeg"),
};

export default images;
